### ISSUE TITLE
Doesn't return the same instance on each call

### ISSUE THREAD

**Issue by sebastiaanluca** [smikhalevski/single-module-instance-webpack-plugin#1]
I ran into the same issue as many before me where I wanted to `require` the same NPM module instance across multiple files. Your package seems like it would fit my needs, but I can't seem to get it to work or maybe I'm misunderstanding what it provides?

In my webpack `plugins` config I've got this:

```
new webpack.optimize.DedupePlugin(),
new SingleModuleInstancePlugin(),
```

Using `require('datatables.net')` for instance in multiple files still returns a new copy of the module each time.

**Comment by smikhalevski** [comment]
Hello Sebastiaan! Can you please provide a sample source which causes a
problem you described? I'll try to resolve it.

**Comment by sebastiaanluca** [comment]
My setup is a bit too extensive to post here altogether, but simply putting `require('datatables.net/js/jquery.dataTables.js')` in file `A.js`, `B.js`, and `C.js` which get built using webpack and saved as `app.js` should return one instance of datatables in all modules, correct?

Can the same be said when A and B get exported as `app.js` and C as `secondary.js` for example, or does webpack / your plugin not know about the other file and its identical requirement for that instance when using multiple JS files?

**Comment by smikhalevski** [comment]
@sebastiaanluca Thank you for your feedback!
1. Yes, your expectations are correct.
2. This depends on how `app.js` and `secondary.js` are created in your config. They can be entry points without commons bundle or the can be named modules. What case do you have?

I also made an investigation in scope of your question and found that current implementation of my plugin handle duplicated transitional dependencies incorrectly. This happens because it relies on string equality of module sources. Ex. A and B both depend C that depends on D. A and B would receive different instances of  C because it has two sources in the target project with different `__webpack_require__` calls to D.
